### ISSUE TITLE
Video setup

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#11]
@andreantonacci, can you please make a suggestion for the recording of clips? This is a good synergy between TSH and this project.

Think about two setups:
- at home recording (with OBS); extra equipment needed?
- studio recording in Tilburg (they also use OBS I think...)

- We need visuals for TSH, but also for this course. Set it up in a way so that we can re-render the course videos in TSH style after this.
- Which equipment do we need?
- How to have our slide deck if we wanna show things? Or use post-processing?

This one looks cool:

https://www.youtube.com/watch?v=V_KcGS4whJc (check this one out in terms of overlays, etc.)

![image](https://user-images.githubusercontent.com/16557730/98953793-6a14b580-24fd-11eb-8079-5e3dffb6e4fb.png)

This one is less ideal, way too traditional:

![image](https://user-images.githubusercontent.com/16557730/98953656-3cc80780-24fd-11eb-96bd-d52af8b75160.png)

I want low effort on my side... I'm not a video editor but a prof ;).

**Comment by hannesdatta** [comment]
@RoyKlaasseBos, also post your ideas here.

**Comment by RoyKlaasseBos** [comment]
## Slides
### Code Snippets
- Most online coding tutorials on Datacamp and YouTube only rely on audio (no screencast in the corner of the screen). I prefer it this way so that you can see most of the screen. On a side note, I like the way Datacamp instructors format coding snippets on their slides (step by step a new block, color, font)
![Screenshot 2020-11-16 at 20 19 34](https://user-images.githubusercontent.com/16261663/99297972-4cbb5080-2849-11eb-8abd-8f6c50cc1067.png)

### Animations
- This bio stats prof has many [great example](https://www.youtube.com/watch?v=FgakZw6K1QQ) on his YouTube channel on how to use animations in PowerPoint. A major advantage of hosting the open education material on YouTube would be usability (i.e., timestamps within the video, cards in which can link between videos) and reaching a larger audience.
![Screenshot 2020-11-16 at 20 14 41](https://user-images.githubusercontent.com/16261663/99297310-60b28280-2848-11eb-9f55-e0e5cfdab25a.png)

## Background
- In my opinion a modern office set-up looks more welcoming than a green screen or any other steril background. [For example, see this one from Colt Steele (878k students)](https://www.udemy.com/course/the-modern-python3-bootcamp/): 
![Screenshot 2020-11-16 at 19 57 58](https://user-images.githubusercontent.com/16261663/99296261-c271ed00-2846-11eb-86b8-01b135ea0b86.png)

Here's another example of an informal background ([Cassie Kozyrkov](https://www.youtube.com/watch?v=GEFxFVESQXc), Google). You only need some good lightning (or a window in front), and an interesting wall of course :-)
![Screenshot 2020-11-16 at 20 33 09](https://user-images.githubusercontent.com/16261663/99299071-f5b67b00-284a-11eb-8a96-eacacb6fbfca.png)

## Live Drawing
- For my econometrics classes I always watched [Ben Lamberts videos (Oxford)](https://www.youtube.com/watch?v=zTG13T_zZyk). This format works especially well if you write down a lot of equations.
![Screenshot 2020-11-16 at 20 27 36](https://user-images.githubusercontent.com/16261663/99298558-2f3ab680-284a-11eb-97d5-63254233d63e.png)

**Comment by RoyKlaasseBos** [comment]
Postponed to later (students of the first cohort will read the course material themselves).

**Comment by RoyKlaasseBos** [comment]
(copied from another issue)

As you pointed out earlier, the advantage of using a code-based system is sustainability of the course material. On that note, LaTeX slides would be my first suggestion (I saw you used those in the LSE presentation). However, I do think they come across as rather formal / academic whereas the image you want to portray with TSH seems more informal (i.e., written for a younger audience). 

## Tutorial slides
Aside from that, LaTeX is especially useful for math equations while oDCM is mostly code and conceptual ideas (not so math heavy). Earlier I referred to the DataCamp course slides as an example on how to format slides (#11 ). Although it's hard to judge from the outside, it does not seem to be based on a code-based system. That's why I looked for an alternative online and stumbled upon [RISE](https://rise.readthedocs.io/en/stable/) which turns Jupyter Notebooks into presentations (see a brief demo [here](https://www.youtube.com/watch?v=utNl9f3gqYQ)). I'd suggest to use these RISE presentations and Jupyter Notebooks for tutorial purposes side by side (i.e., video tutorials/demos -> RISE ~ a la DataCamp; exercises and walk-through notebooks for students -> Jupyter Notebooks). 

## Conceptual/theory slides
Finally, for videos about conceptual ideas (e.g., what is web-scraping) we use the "office-setup" we discussed earlier. In some cases we may want to insert a slide with animations as a video lay-over (audio: your voice video: slides - mixed with speaker shots). For these slides I'd prefer to use animations (e.g. [Statquest](https://www.youtube.com/watch?v=HDCOUXE3HMM)) over bullet-point style. It looks like he uses PowerPoint to create them (I don't think that's an issue as these videos should remain relevant for a long time; don't have to be recreated every other year)

**Comment by hannesdatta** [comment]
@andreantonacci, this is something we thought was cool for videos. any way to add some of these as inspiration on TSH?

**Comment by andreantonacci** [comment]
I agree on the idea of using animations over bullet points. But a talking head also works fine especially if you set up a nice background. You could jump to the animations only when they truly add some value to the speech (complex concepts that require some visualization). How and what to use to create these animations is a much tougher question. Requires some careful investigation (I strongly advocate for consistency in videos, to avoid shooting or editing them again if you change your idea. If you choose a service for these animations, you should commit to it.)
