### ISSUE TITLE
Slide template design

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#20]
- Define how slides are going to be made
- Code-based system

**Comment by RoyKlaasseBos** [comment]
As you pointed out earlier, the advantage of using a code-based system is sustainability of the course material. On that note, LaTeX slides would be my first suggestion (I saw you used those in the LSE presentation). However, I do think they come across as rather formal / academic whereas the image you want to portray with TSH seems more informal (i.e., written for a younger audience). 

## Tutorial slides
Aside from that, LaTeX is especially useful for math equations while oDCM is mostly code and conceptual ideas (not so math heavy). Earlier I referred to the DataCamp course slides as an example on how to format slides (#11 ). Although it's hard to judge from the outside, it does not seem to be based on a code-based system. That's why I looked for an alternative online and stumbled upon [RISE](https://rise.readthedocs.io/en/stable/) which turns Jupyter Notebooks into presentations (see a brief demo [here](https://www.youtube.com/watch?v=utNl9f3gqYQ)). I'd suggest to use these RISE presentations and Jupyter Notebooks for tutorial purposes side by side (i.e., video tutorials/demos -> RISE ~ a la DataCamp; exercises and walk-through notebooks for students -> Jupyter Notebooks). 

## Conceptual/theory slides
Finally, for videos about conceptual ideas (e.g., what is web-scraping) we use the "office-setup" we discussed earlier. In some cases we may want to insert a slide with animations as a video lay-over (audio: your voice video: slides - mixed with speaker shots). For these slides I'd prefer to use animations (e.g. [Statquest](https://www.youtube.com/watch?v=HDCOUXE3HMM)) over bullet-point style. It looks like he uses PowerPoint to create them (I don't think that's an issue as these videos should remain relevant for a long time; don't have to be recreated every other year)
